[package]
name = "custom-shader"
version = "0.1.0"
edition = { workspace = true }
license = "MIT"

[dependencies]
itertools = "0.10.5"
noise = "0.8.2"
bevy = { workspace = true }
bevy_shader_utils = { workspace = true }
