[package]
name = "custom-shader"
version = "0.1.0"
edition = { workspace = true }
license = "MIT"

[dependencies]
itertools = "0.10.5"
noise = "0.8.2"
bevy-inspector-egui = "0.16"
bevy = { workspace = true }
bevy_shader_utils = { workspace = true }

[dev-dependencies]
float-cmp = "0.9.0"
